/**
 * ============================================================
 * app.js — TaskFlow To-Do List Application
 * ============================================================
 *
 * OVERVIEW FOR SIWES INTERNSHIP DOCUMENTATION:
 * ---------------------------------------------
 * This file is the single JavaScript module powering the TaskFlow
 * to-do list application. It demonstrates four core concepts that
 * are essential for any front-end developer to understand:
 *
 *   1. CRUD Operations — Create, Read, Update, Delete
 *   2. DOM Manipulation — dynamically building and modifying HTML
 *   3. Event-Driven Programming — listening for user interactions
 *   4. Data Persistence with localStorage — saving data in the browser
 *
 * The code is written in plain (vanilla) JavaScript with zero
 * external libraries or frameworks, making it ideal for learning.
 *
 * ============================================================
 * SECTION 1: HOW localStorage WORKS (EDUCATIONAL)
 * ============================================================
 *
 * The browser's localStorage API stores data as KEY-VALUE PAIRS
 * where BOTH the key and value must be STRINGS.
 *
 * Problem:  Our tasks are JavaScript objects stored in an array.
 *           Arrays and objects are NOT strings.
 *
 * Solution: We use two built-in JSON methods to convert between
 *           JavaScript data structures and strings:
 *
 *   → JSON.stringify(value)
 *     Converts a JavaScript array/object INTO a JSON string.
 *     Example:
 *       const tasks = [{ id: 1, text: "Learn JS", completed: false }];
 *       const jsonString = JSON.stringify(tasks);
 *       // jsonString is now: '[{"id":1,"text":"Learn JS","completed":false}]'
 *       localStorage.setItem('tasks', jsonString);
 *
 *   → JSON.parse(string)
 *     Converts a JSON string BACK into a JavaScript array/object.
 *     Example:
 *       const raw = localStorage.getItem('tasks');
 *       // raw is: '[{"id":1,"text":"Learn JS","completed":false}]'
 *       const tasks = JSON.parse(raw);
 *       // tasks is now a real JS array we can loop over, push to, etc.
 *
 * IMPORTANT EDGE CASE:
 *   On the very first visit, localStorage.getItem('tasks') returns
 *   null (because nothing has been stored yet). If we pass null to
 *   JSON.parse(), it returns null — NOT an empty array. That's why
 *   in loadTasks() we use:
 *
 *       return JSON.parse(stored) || [];
 *
 *   The || [] is a fallback: if the parsed result is null (falsy),
 *   we default to an empty array so the rest of the code never
 *   crashes from trying to call .push() or .filter() on null.
 *
 * WHY THIS MATTERS:
 *   Without localStorage, every page refresh wipes the task list.
 *   With it, the user's data survives browser restarts. This is
 *   the simplest form of client-side data persistence — more
 *   advanced approaches include IndexedDB, cookies, or a backend
 *   database accessed via fetch/API calls.
 *
 * ============================================================
 * SECTION 2: HOW EVENT LISTENERS ARE ATTACHED (EDUCATIONAL)
 * ============================================================
 *
 * An event listener is a function that "waits" for a specific
 * action (event) to happen on a specific HTML element.
 *
 * Syntax:
 *   element.addEventListener('eventType', handlerFunction);
 *
 * In this app, we attach listeners in two ways:
 *
 * A) DIRECT ATTACHMENT — for elements that exist when the page loads:
 *    Example: the <form> element is always in the HTML.
 *      taskForm.addEventListener('submit', handleAddTask);
 *    When the user submits the form, handleAddTask() runs.
 *
 * B) EVENT DELEGATION — for elements created dynamically:
 *    Task <li> items are generated by JavaScript and can be added
 *    or removed at any time. Instead of attaching listeners to each
 *    new <li>, we attach ONE listener to their parent <ul>:
 *
 *      taskListEl.addEventListener('click', handleTaskListClick);
 *
 *    Inside handleTaskListClick, we inspect event.target to figure
 *    out WHICH child element was clicked (checkbox or delete button).
 *    This pattern is called EVENT DELEGATION and it is both more
 *    efficient and simpler than managing individual listeners.
 *
 *    WHY IT WORKS:
 *    When you click a child element, the click event "bubbles" up
 *    through the DOM tree — from the child, to its parent, to its
 *    grandparent, all the way to <html>. By listening on the parent
 *    <ul>, we catch clicks on any child, including children that
 *    don't exist yet when the listener is attached.
 *
 * ============================================================
 */

// ============================================================
// DOM Element References
// ============================================================
// We grab references to all the HTML elements we need to interact
// with. This is done once at the top for performance (avoids
// repeated DOM lookups) and clarity.

/** @type {HTMLFormElement} The form wrapping the input and add button */
const taskForm = document.getElementById('task-form');

/** @type {HTMLInputElement} The text input where users type new tasks */
const taskInput = document.getElementById('task-input');

/** @type {HTMLUListElement} The <ul> container that holds all task <li> items */
const taskListEl = document.getElementById('task-list');

/** @type {HTMLDivElement} The empty state message shown when no tasks exist */
const emptyState = document.getElementById('empty-state');

/** @type {HTMLButtonElement} Button to bulk-delete all completed tasks */
const clearCompletedBtn = document.getElementById('clear-completed-btn');

// Stat display elements
/** @type {HTMLSpanElement} Displays total task count */
const statTotal = document.getElementById('stat-total');
/** @type {HTMLSpanElement} Displays active (incomplete) task count */
const statActive = document.getElementById('stat-active');
/** @type {HTMLSpanElement} Displays completed task count */
const statDone = document.getElementById('stat-done');

// Filter buttons
/** @type {NodeListOf<HTMLButtonElement>} All three filter buttons (All/Active/Completed) */
const filterButtons = document.querySelectorAll('.filter-btn');


// ============================================================
// Application State
// ============================================================
// These variables represent the "in-memory" state of the app.
// `tasks` is the single source of truth — every render reads
// from this array, and every mutation writes back to it and
// then saves to localStorage.

/**
 * The master array of task objects.
 * Each task has the shape: { id: number, text: string, completed: boolean }
 * Loaded from localStorage on startup.
 * @type {Array<{id: number, text: string, completed: boolean}>}
 */
let tasks = [];

/**
 * The currently active filter. Controls which tasks are visible.
 * Can be 'all', 'active', or 'completed'.
 * @type {string}
 */
let currentFilter = 'all';

/**
 * The key used to store/retrieve tasks in localStorage.
 * Using a constant prevents typos across the codebase.
 * @type {string}
 */
const STORAGE_KEY = 'taskflow_tasks';


// ============================================================
// localStorage Functions (CRUD — the "Storage" layer)
// ============================================================

/**
 * LOAD TASKS FROM localStorage (READ)
 * ------------------------------------
 * This function retrieves the stored JSON string from localStorage,
 * parses it back into a JavaScript array, and returns it.
 *
 * Step-by-step:
 *   1. localStorage.getItem(STORAGE_KEY) returns the raw JSON string,
 *      or null if nothing has been stored under that key yet.
 *   2. JSON.parse() converts the JSON string into a JS array.
 *   3. The `|| []` fallback ensures we always return an array,
 *      even on first visit when getItem returns null.
 *
 * @returns {Array<{id: number, text: string, completed: boolean}>}
 */
function loadTasks() {
    const stored = localStorage.getItem(STORAGE_KEY);

    // JSON.parse(null) returns null, so we default to empty array.
    // This prevents errors like "Cannot read property 'forEach' of null".
    return JSON.parse(stored) || [];
}

/**
 * SAVE TASKS TO localStorage (WRITE)
 * ------------------------------------
 * This function takes our in-memory tasks array, converts it
 * to a JSON string, and writes it to localStorage.
 *
 * Step-by-step:
 *   1. JSON.stringify(tasks) converts the array of objects into
 *      a single string like '[{"id":1,"text":"Buy milk","completed":false}]'.
 *   2. localStorage.setItem(STORAGE_KEY, ...) stores that string
 *      under our chosen key name.
 *
 * We call this function after EVERY mutation (add, toggle, delete)
 * to ensure localStorage always mirrors the in-memory state.
 */
function saveTasks() {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(tasks));
}


// ============================================================
// CRUD Operations
// ============================================================

/**
 * CREATE — Add a new task to the list.
 * -------------------------------------
 * 1. Creates a new task object with a unique ID (timestamp-based).
 * 2. Adds it to the FRONT of the tasks array (newest first).
 * 3. Saves the updated array to localStorage.
 * 4. Re-renders the UI to show the new task.
 *
 * @param {string} text - The task description entered by the user.
 */
function addTask(text) {
    // Create task object. Date.now() gives milliseconds since epoch,
    // which is unique enough for a single-user local app.
    const newTask = {
        id: Date.now(),
        text: text.trim(),
        completed: false
    };

    // unshift() adds to the beginning of the array so new tasks
    // appear at the top of the list (better UX).
    tasks.unshift(newTask);

    // Persist to localStorage immediately after mutation.
    saveTasks();

    // Re-render the task list to reflect the new task.
    renderTasks();
}

/**
 * UPDATE — Toggle a task's completed status.
 * --------------------------------------------
 * Uses Array.find() to locate the task by ID, then flips its
 * `completed` boolean. Saves and re-renders.
 *
 * @param {number} taskId - The unique ID of the task to toggle.
 */
function toggleTask(taskId) {
    // Array.find() returns the first element matching the condition,
    // or undefined if no match is found.
    const task = tasks.find(t => t.id === taskId);

    if (task) {
        // Flip the boolean: true becomes false, false becomes true.
        task.completed = !task.completed;

        // Persist the change.
        saveTasks();

        // Re-render to update visual strikethrough and stats.
        renderTasks();
    }
}

/**
 * DELETE — Remove a single task from the list.
 * ----------------------------------------------
 * Uses Array.filter() to create a NEW array excluding the task
 * with the given ID. We reassign `tasks` to this new array.
 *
 * Why filter() instead of splice()?
 *   - filter() is declarative and reads more clearly.
 *   - splice() mutates in-place and requires finding the index first.
 *   - Both work; filter() is more idiomatic in modern JS.
 *
 * @param {number} taskId - The unique ID of the task to delete.
 */
function deleteTask(taskId) {
    // filter() keeps only tasks whose ID does NOT match the one
    // we want to delete.
    tasks = tasks.filter(t => t.id !== taskId);

    // Persist and re-render.
    saveTasks();
    renderTasks();
}

/**
 * DELETE (BULK) — Remove all completed tasks.
 * ---------------------------------------------
 * Filters the array to keep only incomplete (active) tasks.
 */
function clearCompleted() {
    tasks = tasks.filter(t => !t.completed);

    saveTasks();
    renderTasks();
}


// ============================================================
// Rendering (DOM Manipulation)
// ============================================================

/**
 * RENDER TASKS — Build and display the task list in the DOM.
 * -----------------------------------------------------------
 * This is the main "read" function. It:
 *   1. Determines which tasks to show based on the active filter.
 *   2. Clears the existing <ul> content.
 *   3. Creates new <li> elements for each visible task.
 *   4. Updates stats and UI state (empty message, clear button).
 *
 * DESIGN DECISION — Full Re-render vs. Incremental Updates:
 *   We clear the list and rebuild it entirely on each call.
 *   For a small local app (<100 tasks), this is perfectly fine
 *   and much simpler than tracking individual DOM changes.
 *   Frameworks like React optimize this with a Virtual DOM,
 *   but for a vanilla JS portfolio project, clarity wins.
 */
function renderTasks() {
    // --- Step 1: Apply the current filter ---
    let visibleTasks;

    switch (currentFilter) {
        case 'active':
            visibleTasks = tasks.filter(t => !t.completed);
            break;
        case 'completed':
            visibleTasks = tasks.filter(t => t.completed);
            break;
        default:
            visibleTasks = tasks; // 'all' — show everything
    }

    // --- Step 2: Clear the existing list ---
    // innerHTML = '' removes all child nodes efficiently.
    taskListEl.innerHTML = '';

    // --- Step 3: Create a <li> for each visible task ---
    visibleTasks.forEach(task => {
        // Create the list item element
        const li = createTaskElement(task);
        taskListEl.appendChild(li);
    });

    // --- Step 4: Update UI state ---
    updateStats();
    toggleEmptyState(visibleTasks.length === 0);
    toggleClearButton();
}

/**
 * CREATE TASK ELEMENT — Build a single task <li> node.
 * ------------------------------------------------------
 * This function constructs the following HTML structure
 * programmatically (without innerHTML for security):
 *
 *   <li class="task-item [completed]" data-task-id="123456">
 *       <input type="checkbox" class="task-checkbox" [checked]>
 *       <span class="task-text">Task description here</span>
 *       <button class="delete-btn" aria-label="Delete task">
 *           <svg>...</svg>
 *       </button>
 *   </li>
 *
 * WHY data-* ATTRIBUTES?
 *   HTML5 data attributes (data-task-id) let us embed custom
 *   data directly on DOM elements. When a user clicks a checkbox
 *   or delete button, we can read the task's ID from the closest
 *   parent <li>'s dataset without needing a lookup table.
 *
 * @param {Object} task - The task object { id, text, completed }.
 * @returns {HTMLLIElement} The fully constructed list item element.
 */
function createTaskElement(task) {
    // --- Create the <li> container ---
    const li = document.createElement('li');
    li.className = `task-item${task.completed ? ' completed' : ''}`;
    li.setAttribute('data-task-id', task.id);
    li.setAttribute('role', 'listitem');

    // --- Create the checkbox <input> ---
    const checkbox = document.createElement('input');
    checkbox.type = 'checkbox';
    checkbox.className = 'task-checkbox';
    checkbox.checked = task.completed;
    checkbox.setAttribute('aria-label', `Mark "${task.text}" as ${task.completed ? 'incomplete' : 'complete'}`);

    // --- Create the task text <span> ---
    const textSpan = document.createElement('span');
    textSpan.className = 'task-text';
    // textContent is safer than innerHTML — it escapes HTML entities
    // automatically, preventing XSS (cross-site scripting) attacks.
    textSpan.textContent = task.text;

    // --- Create the delete <button> ---
    const deleteBtn = document.createElement('button');
    deleteBtn.className = 'delete-btn';
    deleteBtn.setAttribute('aria-label', `Delete task: ${task.text}`);
    // We use innerHTML here only for the SVG icon (static, trusted content).
    deleteBtn.innerHTML = `
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"
             fill="none" stroke="currentColor" stroke-width="2"
             stroke-linecap="round" stroke-linejoin="round">
            <polyline points="3 6 5 6 21 6"></polyline>
            <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4
                     a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
        </svg>
    `;

    // --- Assemble the <li> ---
    li.appendChild(checkbox);
    li.appendChild(textSpan);
    li.appendChild(deleteBtn);

    return li;
}

/**
 * UPDATE STATS — Refresh the stats bar numbers.
 * ------------------------------------------------
 * Counts total, active, and completed tasks and updates
 * the corresponding <span> elements' text content.
 */
function updateStats() {
    const total = tasks.length;
    const completed = tasks.filter(t => t.completed).length;
    const active = total - completed;

    statTotal.textContent = total;
    statActive.textContent = active;
    statDone.textContent = completed;
}

/**
 * TOGGLE EMPTY STATE — Show or hide the "No tasks yet" message.
 *
 * @param {boolean} isEmpty - Whether the visible task list is empty.
 */
function toggleEmptyState(isEmpty) {
    if (isEmpty) {
        emptyState.removeAttribute('hidden');
    } else {
        emptyState.setAttribute('hidden', '');
    }
}

/**
 * TOGGLE CLEAR BUTTON — Show or hide the "Clear Completed" button.
 * Only visible when there is at least one completed task.
 */
function toggleClearButton() {
    const hasCompleted = tasks.some(t => t.completed);

    if (hasCompleted) {
        clearCompletedBtn.removeAttribute('hidden');
    } else {
        clearCompletedBtn.setAttribute('hidden', '');
    }
}


// ============================================================
// Event Handlers
// ============================================================

/**
 * HANDLE ADD TASK — Processes the form submission.
 * ---------------------------------------------------
 * This is called when the user presses Enter or clicks the + button.
 *
 * event.preventDefault() stops the browser's default form behavior
 * (which would reload the page). In a single-page app, we handle
 * everything in JavaScript instead.
 *
 * @param {SubmitEvent} event - The form submission event.
 */
function handleAddTask(event) {
    // Prevent the default form submission (page reload).
    event.preventDefault();

    // Read and trim the input value.
    const text = taskInput.value.trim();

    // Guard clause: don't add empty tasks.
    if (!text) return;

    // Delegate to the CREATE function.
    addTask(text);

    // Clear the input field and re-focus it for rapid entry.
    taskInput.value = '';
    taskInput.focus();
}

/**
 * HANDLE TASK LIST CLICK — Event delegation handler.
 * -----------------------------------------------------
 * Instead of attaching listeners to each checkbox and delete button
 * individually, we attach ONE listener to the parent <ul> element.
 *
 * When any child is clicked, the event bubbles up to the <ul>.
 * We then inspect event.target to determine what was clicked:
 *
 *   - If it's a checkbox → toggle that task's completion status.
 *   - If it's a delete button (or its SVG child) → delete that task.
 *
 * element.closest('.selector') walks UP the DOM tree to find the
 * nearest ancestor matching the selector. This is essential for
 * the delete button because the user might click the <svg> icon
 * inside the button, not the button itself.
 *
 * @param {MouseEvent} event - The click event.
 */
function handleTaskListClick(event) {
    // Find the closest parent <li> to get the task's ID.
    const taskItem = event.target.closest('.task-item');

    // If the click wasn't inside a task item, ignore it.
    if (!taskItem) return;

    // Parse the task ID from the data attribute.
    // parseInt() converts the string "1687..." back to a number,
    // since data attributes are always strings.
    const taskId = parseInt(taskItem.dataset.taskId, 10);

    // --- Check if a CHECKBOX was clicked ---
    if (event.target.classList.contains('task-checkbox')) {
        toggleTask(taskId);
        return;
    }

    // --- Check if a DELETE BUTTON (or its child SVG) was clicked ---
    const deleteBtn = event.target.closest('.delete-btn');
    if (deleteBtn) {
        // Add the removal animation class.
        taskItem.classList.add('removing');

        // Wait for the CSS animation to finish before actually
        // removing the task from the data and DOM.
        // 350ms matches the duration of the taskSlideOut animation.
        taskItem.addEventListener('animationend', () => {
            deleteTask(taskId);
        }, { once: true });
        // { once: true } automatically removes the listener after
        // it fires once, preventing memory leaks.
    }
}

/**
 * HANDLE FILTER CLICK — Switches the active filter view.
 * --------------------------------------------------------
 * Reads the filter type from the button's data-filter attribute.
 * Updates the UI to highlight the active filter button.
 *
 * @param {MouseEvent} event - The click event on a filter button.
 */
function handleFilterClick(event) {
    // Ignore clicks that aren't on a filter button.
    if (!event.target.classList.contains('filter-btn')) return;

    // Read the filter type: 'all', 'active', or 'completed'.
    currentFilter = event.target.dataset.filter;

    // Update the visual "active" state on the filter buttons.
    // Remove 'active' class from all, then add it to the clicked one.
    filterButtons.forEach(btn => btn.classList.remove('active'));
    event.target.classList.add('active');

    // Re-render with the new filter applied.
    renderTasks();
}

/**
 * HANDLE CLEAR COMPLETED — Removes all completed tasks.
 */
function handleClearCompleted() {
    clearCompleted();
}


// ============================================================
// SECTION 3: Attaching Event Listeners (EDUCATIONAL)
// ============================================================
//
// Below is where we "wire up" the application. Each call to
// addEventListener() connects a specific DOM event to one of
// the handler functions defined above.
//
// IMPORTANT: This code runs ONCE when the script loads.
// The listeners persist for the lifetime of the page.
//
// ---- WHY THESE SPECIFIC EVENTS? ----
//
// 'submit' on the form:
//   Fires when the user presses Enter inside the input OR
//   clicks the submit button. Covers both interaction paths
//   with a single listener. We use preventDefault() inside
//   the handler to stop the page from reloading.
//
// 'click' on taskListEl (event delegation):
//   Fires for ANY click inside the <ul>, including on child
//   elements like checkboxes and delete buttons. We use
//   event.target and .closest() to figure out what was clicked.
//   This is more efficient than attaching listeners to every
//   individual task element, especially since tasks are
//   dynamically created and destroyed.
//
// 'click' on each filter button:
//   We use a forEach loop over the NodeList of filter buttons
//   to attach a click handler to each one. Alternatively, we
//   could use event delegation on the parent <nav>, but with
//   only 3 buttons, direct attachment is simpler and clearer.
//
// 'click' on the clearCompletedBtn:
//   A straightforward direct attachment — one button, one action.
//

// Wire up the form submission (handles both Enter key and button click).
taskForm.addEventListener('submit', handleAddTask);

// Wire up click handling for the entire task list (event delegation).
// This single listener handles BOTH checkbox toggles and delete clicks.
taskListEl.addEventListener('click', handleTaskListClick);

// Wire up each filter button individually.
filterButtons.forEach(btn => {
    btn.addEventListener('click', handleFilterClick);
});

// Wire up the "Clear Completed" button.
clearCompletedBtn.addEventListener('click', handleClearCompleted);


// ============================================================
// Initialization — App Startup
// ============================================================
//
// This code runs once when the page first loads (or is refreshed).
// It loads any previously saved tasks from localStorage and renders
// them into the DOM. This is what makes the app "persistent" — the
// user sees their tasks again after closing and reopening the browser.

/**
 * INIT — Bootstrap the application.
 * ------------------------------------
 * 1. Load tasks from localStorage into the in-memory array.
 * 2. Render the initial task list to the DOM.
 *
 * This function is called immediately below its definition
 * (IIFE-style, but we keep it named for clarity in stack traces).
 */
function init() {
    // Load saved tasks from localStorage.
    // On first visit, this returns [] (empty array).
    tasks = loadTasks();

    // Render the loaded tasks into the DOM.
    renderTasks();

    // Focus the input field so the user can start typing immediately.
    taskInput.focus();
}

// Start the application!
init();
